from m2.stack import Stack


def reconstruct_path(parent, source, destination):
    """
    Reconstruct the route from source to destination
    using the parent dictionary generated by a routing algorithm.

    Parameters:
        parent: Dictionary containing each node's predecessor.
        source: Starting node ID.
        destination: Destination node ID.

    Returns:
        List containing the route from source to destination.
        Returns an empty list if the destination is unreachable.
    """

    if source == destination:
        return [source]

    if destination not in parent:
        return []

    stack = Stack()
    current = destination

    while current != source:
        stack.push(current)

        if current not in parent:
            return []

        current = parent[current]

    stack.push(source)

    path = []

    while not stack.is_empty():
        path.append(stack.pop())

    return path